name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      COMPILE_API_LEVEL: 29
      ANDROID_BUILD_TOOLS_VERSION: 29.0.2

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8

    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Install SDK packages
      run: |
        sdkmanager "platforms;android-${{ env.COMPILE_API_LEVEL }}" \
                   "build-tools;${{ env.ANDROID_BUILD_TOOLS_VERSION }}"

    - name: Run Gradle build
      run: |
        ./gradlew clean
        ./gradlew :presentation:assembleWithAnalyticsRelease :presentation:bundleWithAnalyticsRelease -PtestCoverageEnabled=true

    - name: Upload build artifacts
      if: success() && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          presentation/build/outputs/bundle/withAnalyticsRelease/presentation.aab
          presentation/build/outputs/apk/withAnalytics/release/presentation-withAnalytics-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
