name: Build and Release
on:
  workflow_dispatch:  # Manually triggered workflow
  push:
    tags:
      - "v*"
jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Set execution flag for gradlew
        run: chmod +x gradlew
      
      - name: Build APK
        run: |
          ./gradlew assembleNoAnalyticsRelease 
      
      - name: Rename APK
        run: mv presentation/build/outputs/apk/noAnalytics/release/*.apk presentation/build/outputs/apk/noAnalytics/release/QUIK-noAnalytics-release.apk
      
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: quik-apk
          path: presentation/build/outputs/apk/noAnalytics/release/QUIK-noAnalytics-release.apk
          # This artifact will be available for download for 90 days (default)

  release:
    name: Release APK
    needs: apk
    if: startsWith(github.ref, 'refs/tags/v')  # Only run on tag pushes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set release datetime
        run: echo "DATETIME=$(date +'%d-%m-%y_%s')" >> $GITHUB_ENV
    
      - name: Download APK from build
        uses: actions/download-artifact@v4
        with:
          name: quik-apk
          path: ./downloaded-apk
          
      - name: Create and upload release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: ${{ github.ref_name }}
          files: ./downloaded-apk/QUIK-noAnalytics-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Validate Fastlane Supply Metadata
        uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2.0.0
        with:
          fastlaneDir: ./metadata
